### ISSUE TITLE
New provider powerdns (pdns)

### ISSUE THREAD

**Issue by samip5** [cloudydeno/kubernetes-dns-sync#2]
It would be awesome if you could add pdns provider too. :)

**Comment by danopia** [comment]
Hi, thanks for the interest and I hope you see something here that draws interest because otherwise this project is a bit bare bones :) as you are the first person to file anything on it yet.

It looks like this is the API of interest, specifically to update records? https://doc.powerdns.com/authoritative/http-api/zone.html#patch--servers-server_id-zones-zone_id

Providers should be pretty simple integrations however I'd still want to verify on my own before uploading code so fortunately it looks like this is a process that I can run locally for testing.

**Comment by samip5** [comment]
That would be correct after finding out the external-dns short comings regarding IPv6 support.

**Comment by danopia** [comment]
I just pushed what appears to be working PowerDNS support for **A/AAAA/TXT**, in case you're still interested in trying out this project. The latest container at `ghcr.io/cloudydeno/kubernetes-dns-sync` includes this support.

I tested with this `config.toml` file:

```toml
[[source]]
type = "crd"

[[source]]
type = "ingress"

[[provider]]
type = "powerdns"
api_endpoint = "http://localhost:7070/api/"

[registry]
type = "txt"
txt_prefix = "_registry."
txt_owner_id = "demo"
```

The API key is read from the `POWERDNS_API_KEY` environment variable.

The zones have to exist already because I'm only managing rrsets. 

`MX` and `CNAME` records **do not work** in this first pass (though they'll be pretty easy to fix, just formatting issues).

**Comment by samip5** [comment]
Do you have an Helm chart for this yet?

**Comment by samip5** [comment]
Do you have an Helm chart for this yet?

**Comment by samip5** [comment]
Do you have an Helm chart for this yet?

**Comment by danopia** [comment]
No, sorry, I don't use helm on my personal cluster, rather `kustomize`.

* The easiest way to test stuff quickly is probably installing [Deno](https://deno.land/) and running a command like `POWERDNS_API_KEY=changeme deno run --allow-all controller/mod.ts --once` so the program runs once interactively and exits. 

* If you want to test on-cluster, first run with `--dry-run` instead so the program loops & prints but doesn't try making any actual changes. (The default is to prompt for changes, which isn't useful in a pod.)

    I should document running on-cluster but it hasn't come up yet, so below are some YAML snippets.

If you have further questions about running this, we could 'huddle' on the Kubernetes slack.

The container would be something like:

```yaml
      - name: app
        image: ghcr.io/cloudydeno/kubernetes-dns-sync
        args:
        - --dry-run
        envFrom:
        - secretRef:
            name: dns-sync-credentials-d49ch6h2f7
        securityContext:
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /src/kubernetes-dns-sync/config.toml
          name: cfgmap
          subPath: config.toml
```

The RBAC from external-dns is probably fine, but for completeness here's my `ClusterRole`, this includes grants for the cert-manager ACME integration.

```yaml
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints/status
  verbs:
  - '*'
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges/status
  verbs:
  - '*'
```

**Comment by samip5** [comment]
> No, sorry, I don't use helm on my personal cluster, rather `kustomize`.
> 
> * The easiest way to test stuff quickly is probably installing [Deno](https://deno.land/) and running a command like `POWERDNS_API_KEY=changeme deno run --allow-all controller/mod.ts --once` so the program runs once interactively and exits.
> * If you want to test on-cluster, first run with `--dry-run` instead so the program loops & prints but doesn't try making any actual changes. (The default is to prompt for changes, which isn't useful in a pod.)
>   I should document running on-cluster but it hasn't come up yet, so below are some YAML snippets.
> 
> If you have further questions about running this, we could 'huddle' on the Kubernetes slack.
> 
> The container would be something like:
> 
> ```yaml
>       - name: app
>         image: ghcr.io/cloudydeno/kubernetes-dns-sync
>         args:
>         - --dry-run
>         envFrom:
>         - secretRef:
>             name: dns-sync-credentials-d49ch6h2f7
>         securityContext:
>           capabilities:
>             drop:
>             - ALL
>         volumeMounts:
>         - mountPath: /src/kubernetes-dns-sync/config.toml
>           name: cfgmap
>           subPath: config.toml
> ```
> 
> The RBAC from external-dns is probably fine, but for completeness here's my `ClusterRole`, this includes grants for the cert-manager ACME integration.
> 
> ```yaml
> rules:
> - apiGroups:
>   - ""
>   resources:
>   - services
>   - pods
>   - nodes
>   verbs:
>   - get
>   - watch
>   - list
> - apiGroups:
>   - networking.k8s.io
>   resources:
>   - ingresses
>   verbs:
>   - get
>   - watch
>   - list
> - apiGroups:
>   - externaldns.k8s.io
>   resources:
>   - dnsendpoints
>   verbs:
>   - get
>   - watch
>   - list
> - apiGroups:
>   - externaldns.k8s.io
>   resources:
>   - dnsendpoints/status
>   verbs:
>   - '*'
> - apiGroups:
>   - acme.cert-manager.io
>   resources:
>   - challenges
>   verbs:
>   - get
>   - watch
>   - list
> - apiGroups:
>   - acme.cert-manager.io
>   resources:
>   - challenges/status
>   verbs:
>   - '*'
> ```

So what does your actual kustomization look like for it?

**Comment by samip5** [comment]
Okey, I tested it out, doesn't work properly.

Pod yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: dns-sync
  namespace: networking
spec:
  serviceAccountName: sa-dns-sync
  volumes:
    - name: configmap-volume
      configMap:
        name: dns-sync-creds
  containers:
    - name: app
      image: ghcr.io/cloudydeno/kubernetes-dns-sync
      args:
        - --dry-run
      env:
        - name: POWERDNS_API_KEY
          value: ${PDNS_SAMIPSOLUTIONS_API_KEY}
      securityContext:
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /src/kubernetes-dns-sync/config.toml
          name: configmap-volume
          subPath: config.toml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - "amd64"
```
rbac.yaml:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dns-sync
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-sync
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - externaldns.k8s.io
    resources:
      - dnsendpoints/status
    verbs:
      - '*'
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - challenges
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - challenges/status
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-sync
roleRef:
  kind: ClusterRole
  name: dns-sync
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sa-dns-sync
    namespace: networking
```



Error log:
```
--- 2021-09-30T01:25:47.301Z via schedule
--> Loading desired records from 2 sources...
error: Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 4
    const resp = await this.#client.performRequest({
              ^
    at parse (<anonymous>)
    at packageData (deno:ext/fetch/22_body.js:313:16)
    at Response.json (deno:ext/fetch/22_body.js:253:18)
    at async ExternaldnsV1alpha1Api.getDNSEndpointListForAllNamespaces (https://deno.land/x/kubernetes_apis@v0.3.1/external-dns/externaldns.k8s.io@v1alpha1/mod.ts:25:15)
    at async WatchLister.listFromUpstream (file:///src/kubernetes-dns-sync/common/watch-lister.ts:20:17)
    at async WatchLister.getFreshList (file:///src/kubernetes-dns-sync/common/watch-lister.ts:31:15)
    at async CrdSource.Endpoints (file:///src/kubernetes-dns-sync/sources/crd.ts:23:22)
    at async file:///src/kubernetes-dns-sync/controller/mod.ts:43:20
    at async Promise.all (index 0)
    at async file:///src/kubernetes-dns-sync/controller/mod.ts:42:22
```
